config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
	# attr_accessible :name, :email

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }
	before_save { |user| user.email = email.downcase }
	validates :password, length: { minimum: 6 }
	validates :password_confirmation, presence: true

	has_secure_password

	before_save { |user| user.email = email.downcase }
	before_save :create_remember_token

	private

		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

		def create_remember_token
			self.remember_token = SecureRandom.urlsafe_base64
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_email(params[:session][:email])

		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end

	# def session_params
 #  	params.require(:session).permit(:email, :password)
 #  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

	def show
		@user = User.find(params[:id])
		puts @user
	end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	# puts params
  	if @user.save
  		sign_in @user
  		flash[:success] = "Welcome to the Sample App!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
  	else
  		render 'edit'
  	end
  end 

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  private

  def signed_in_user
    store_location
    redirect_to signin_path, notice: "Please sign in." unless signed_in?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "Ruby on Rails Sample App"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

	def sign_in(user)
		visit signin_path
		fill_in "Email", with: user.email
		fill_in "Password", with: user.password
		click_button "Sign in"
		# Sign in when not using Capybara as well. 
		cookies[:remember_token] = user.remember_token
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user= (user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def current_user?(user)
		user == current_user
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.fullpath
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	Koty
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
	<header class ="navbar navbar-fixed-top">
		<div class ="navbar-inner">
			<div class="container">
				<%= link_to "sample app", root_path, id: "logo" %>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to( "Home", root_path ) %></li>
						<li><%= link_to( "Help", help_path ) %></li>
						<% if signed_in? %>
							<li><%= link_to("Users", users_path) %></li>
							<li id="fat-menu" class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									Account <b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li><%= link_to("Profile", current_user) %></li>
									<li><%= link_to("Settings", edit_user_path(current_user)) %></li>
									<li class="divider"></li>
									<li>
										<%= link_to("Sign out", signout_path , method: "delete") %>
									</li>
								</ul>
							</li>
							<% else %>
							<li><%= link_to( "Sign in", signin_path ) %></li>
							<% end %>
					</ul>
				</nav>
			</div>
		</div>
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li> <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<title>Ruby on Rails Sample App | <%= yield(:title) %></title>
<h1>About Us</h1> 

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %> 
<title>Ruby on Rails Sample App | <%= yield(:title) %></title>
<h1>Contact</h1>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<title>Ruby on Rails Sample App | <%= yield(:title) %></title>
<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<!-- <title>Ruby on Rails Sample App | <%= yield(:title) %></title> -->
<div class="center hero-unit">
	<h1>Sample App</h1>
	
	<%= link_to("Sign up now", new_user_path, class: "btn btn-large btn-primary") %>
</div>

<%= link_to image_tag("https://pbs.twimg.com/profile_images/691206086955790336/CDMbA57p.png", alt: "Rails"), "#" %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 52 %>
	<%= link_to user.name, user %> 
	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to("delete", user, method: :delete, confirm: "You sure?") %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<title>Ruby on Rails Sample App | <%= yield(:title) %></title>
<h1>Update your profile</h1>
	<div class="row">
		<div class="span6 offset3"> 
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %> 

			<%= f.label :name %>
			<%= f.text_field :name %> 

			<%= f.label :email %>
			<%= f.text_field :email %> 

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>

		<% end %>
			<%= gravatar_for @user %>
		<a href="http://gravatar.com/emails">change</a> 
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %> 
<h1>All users</h1>

<%= will_paginate %>
	<ul class="users">
		<%= render @users %>
	</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<title>Ruby on Rails Sample App | <%= yield(:title) %></title>
<h1>Sign up</h1>


<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>	
		<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
	
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<title>Ruby on Rails Sample App | <%= yield(:title) %></title>

<div class="row">
	<aside class="span4">
		<section>
			<h1> 
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>